"""export settings fields

Revision ID: 0e0d8473fdc4
Revises: 187f131ddd0d
Create Date: 2026-08-05 21:03:18.163705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0d8473fdc4'
down_revision: Union[str, Sequence[str], None] = '187f131ddd0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('default_export_template', sa.String(length=300), nullable=True))
    op.add_column('app_settings', sa.Column('default_export_separator', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'default_export_separator')
    op.drop_column('app_settings', 'default_export_template')
    # ### end Alembic commands ###
