"""asset custom fields

Revision ID: 6277acdf5024
Revises: 2510efebe2bb
Create Date: 2026-08-12 01:22:27.725017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6277acdf5024'
down_revision: Union[str, Sequence[str], None] = '2510efebe2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_custom_field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type_id', 'name', name='uq_custom_field_def_type_name')
    )
    op.create_index(op.f('ix_asset_custom_field_definitions_asset_type_id'), 'asset_custom_field_definitions', ['asset_type_id'], unique=False)
    op.create_table('asset_custom_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['definition_id'], ['asset_custom_field_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'definition_id', name='uq_custom_field_value_asset_def')
    )
    op.create_index(op.f('ix_asset_custom_field_values_asset_id'), 'asset_custom_field_values', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_custom_field_values_definition_id'), 'asset_custom_field_values', ['definition_id'], unique=False)
    op.add_column(
        'asset_history',
        sa.Column('custom_field_values', sa.JSON(), server_default='[]', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_history', 'custom_field_values')
    op.drop_index(op.f('ix_asset_custom_field_values_definition_id'), table_name='asset_custom_field_values')
    op.drop_index(op.f('ix_asset_custom_field_values_asset_id'), table_name='asset_custom_field_values')
    op.drop_table('asset_custom_field_values')
    op.drop_index(op.f('ix_asset_custom_field_definitions_asset_type_id'), table_name='asset_custom_field_definitions')
    op.drop_table('asset_custom_field_definitions')
    # ### end Alembic commands ###
