"""remove backup tables

Revision ID: 6b15514cbcfe
Revises: 21f4caeb4b52
Create Date: 2026-08-16 18:14:21.259106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b15514cbcfe'
down_revision: Union[str, Sequence[str], None] = '21f4caeb4b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backup_recipients_backup_settings_id'), table_name='backup_recipients')
    op.drop_table('backup_recipients')
    op.drop_index(op.f('ix_backup_runs_created_at'), table_name='backup_runs')
    op.drop_table('backup_runs')
    op.drop_table('backup_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('interval_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('credentials', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('backup_settings_pkey'))
    )
    op.create_table('backup_recipients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('backup_settings_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipient_identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['backup_settings_id'], ['backup_settings.id'], name=op.f('backup_recipients_backup_settings_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('backup_recipients_pkey')),
    sa.UniqueConstraint('backup_settings_id', 'recipient_identifier', name=op.f('uq_backup_recipients_settings_identifier'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_backup_recipients_backup_settings_id'), 'backup_recipients', ['backup_settings_id'], unique=False)
    op.create_table('backup_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trigger', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('delivery_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('triggered_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('backup_settings_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['backup_settings_id'], ['backup_settings.id'], name=op.f('backup_runs_backup_settings_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('backup_runs_triggered_by_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('backup_runs_pkey'))
    )
    op.create_index(op.f('ix_backup_runs_created_at'), 'backup_runs', ['created_at'], unique=False)
    # ### end Alembic commands ###
