"""asset naming rules and scoped inventory uniqueness

Revision ID: bd925cf3210b
Revises: 0e0d8473fdc4
Create Date: 2026-08-06 22:50:57.869669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd925cf3210b'
down_revision: Union[str, Sequence[str], None] = '0e0d8473fdc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_naming_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('name_result', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type_id', 'serial_number', name='uq_naming_rule_type_serial')
    )
    op.create_index(op.f('ix_asset_naming_rules_asset_type_id'), 'asset_naming_rules', ['asset_type_id'], unique=False)
    op.create_index(op.f('ix_asset_naming_rules_serial_number'), 'asset_naming_rules', ['serial_number'], unique=False)

    # SQLite can't ALTER a constraint in place: the original `UNIQUE (inventory_number)`
    # was declared inline with no name, so batch mode needs a naming convention to
    # address it when rebuilding the table.
    naming_convention = {"uq": "uq_%(table_name)s_%(column_0_name)s"}
    with op.batch_alter_table(
        "assets", naming_convention=naming_convention, recreate="always"
    ) as batch_op:
        batch_op.drop_constraint("uq_assets_inventory_number", type_="unique")
        batch_op.create_unique_constraint(
            "uq_assets_inventory_number_asset_type", ["inventory_number", "asset_type_id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    naming_convention = {"uq": "uq_%(table_name)s_%(column_0_name)s"}
    with op.batch_alter_table(
        "assets", naming_convention=naming_convention, recreate="always"
    ) as batch_op:
        batch_op.drop_constraint("uq_assets_inventory_number_asset_type", type_="unique")
        batch_op.create_unique_constraint("uq_assets_inventory_number", ["inventory_number"])
    op.drop_index(op.f('ix_asset_naming_rules_serial_number'), table_name='asset_naming_rules')
    op.drop_index(op.f('ix_asset_naming_rules_asset_type_id'), table_name='asset_naming_rules')
    op.drop_table('asset_naming_rules')
    # ### end Alembic commands ###
